### ISSUE TITLE
Installation R 4.0.4 trouble

### ISSUE THREAD

**Issue by mikecuoco** [vinay-swamy/scPOP#1]
Hi @vinay-swamy, nice to see you on GitHub! 

I would love to try your tool on my data. Can you recommend a good way to install it? I am currently working in R 4.0.4 and it looks like `devtools::install_github("vinay-swamy/scPOP")` is getting caught with your `RcppExports.o`. Let me know if you'd like me to provide additional error messages.

Mike

**Comment by vinay-swamy** [comment]
I was missing a dependency for RANN, added it to the description. Was able to get the up-to-date version to install on R 4.0.4 with out any problems, so if it still doesn't work post the error messages and I'll take a look

**Comment by mikecuoco** [comment]
@vinay-swamy thanks! All set. I also found I had to enable C+11 mode in my compiler with `Sys.setenv("PKG_CXXFLAGS"="-std=c++11")` for the installation to succeed.
